name: Build and Zip Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -f ./code/DOCKERFILE -t flask-crud-app ./ 

      # Optional: Save Docker image as tar (uncomment if needed)
      # - name: Save Docker image as tar
      #   run: docker save flask-crud-app -o flask-crud-app.tar

      # Optional: Zip the image tarball (uncomment if needed)
      # - name: Zip the image tarball
      #   run: zip flask-crud-app.zip flask-crud-app.tar

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Log in to ACR
        run: |
          az acr login --name ${{secrets.ACR_NAME}}

      - name: Tag Docker image for ACR
        run: |
          docker tag flask-crud-app ${{secrets.ACR_NAME}}.azurecr.io/flask-crud-app:latest

      - name: Push Docker image to ACR
        run: |
          docker push ${{secrets.ACR_NAME}}.azurecr.io/flask-crud-app:latest